name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti dengan nama cabang utama Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Ganti dengan versi PHP yang sesuai

    - name: Install Composer Dependencies
      run: |
        composer install --no-interaction --prefer-dist

    - name: Build and Deploy
      run: |
        cp index.php ./

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
