name: PHP CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run PHP
      run: php index.php  # Sesuaikan dengan nama file PHP Anda
